version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    environment:
      - WATCHPACK_POLLING=TRUE
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app